from .auth_routes import auth_bp
from .announcement_routes import announcement_bp
from .assessment_routes import assessment_bp
from .referral_routes import referral_bp
from .profile_routes import profile_bp
from .notification_bp import notification_bp
from .recovery_routes import recovery_bp
from .admin_routes import admin_bp
from .consultation_routes import consultation_bp
